"""Initial schema with indexes

Revision ID: 3a78ca2ad280
Revises: 
Create Date: 2025-12-03 03:25:52.771858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a78ca2ad280'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('highest', sa.Float(), nullable=True),
    sa.Column('lowest', sa.Float(), nullable=True),
    sa.Column('order_count', sa.BigInteger(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_history_region_id'), 'market_history', ['region_id'], unique=False)
    op.create_index('ix_market_history_region_type_date', 'market_history', ['region_id', 'type_id', 'date'], unique=False)
    op.create_index(op.f('ix_market_history_type_id'), 'market_history', ['type_id'], unique=False)
    op.create_table('market_orders',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Text(), nullable=True),
    sa.Column('volume_remain', sa.Integer(), nullable=True),
    sa.Column('is_buy_order', sa.Integer(), nullable=True),
    sa.Column('issued', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('min_volume', sa.Integer(), nullable=True),
    sa.Column('range', sa.String(), nullable=True),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_market_orders_region_id'), 'market_orders', ['region_id'], unique=False)
    op.create_index(op.f('ix_market_orders_type_id'), 'market_orders', ['type_id'], unique=False)
    op.create_index('ix_market_orders_type_region_buy_issued', 'market_orders', ['type_id', 'region_id', 'is_buy_order', 'issued'], unique=False)
    op.create_index(op.f('ix_market_orders_updated_at'), 'market_orders', ['updated_at'], unique=False)
    op.create_table('region_etags',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('etag', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('region_id', 'page')
    )
    op.create_table('region_fetch_status',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('last_fetch_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fetch_completed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fetch_success', sa.Boolean(), nullable=True),
    sa.Column('orders_fetched', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('region_id')
    )
    op.create_table('sde_market_groups',
    sa.Column('market_group_id', sa.Integer(), nullable=False),
    sa.Column('parent_group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('has_types', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('market_group_id')
    )
    op.create_index(op.f('ix_sde_market_groups_parent_group_id'), 'sde_market_groups', ['parent_group_id'], unique=False)
    op.create_table('sde_regions',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('region_id')
    )
    op.create_index(op.f('ix_sde_regions_name'), 'sde_regions', ['name'], unique=False)
    op.create_table('sde_solar_system_jumps',
    sa.Column('from_solar_system_id', sa.Integer(), nullable=False),
    sa.Column('to_solar_system_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('from_solar_system_id', 'to_solar_system_id')
    )
    op.create_table('sde_solar_systems',
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('security', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_sde_solar_systems_name'), 'sde_solar_systems', ['name'], unique=False)
    op.create_index(op.f('ix_sde_solar_systems_region_id'), 'sde_solar_systems', ['region_id'], unique=False)
    op.create_table('sde_stations',
    sa.Column('station_id', sa.BigInteger(), nullable=False),
    sa.Column('solar_system_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_index(op.f('ix_sde_stations_name'), 'sde_stations', ['name'], unique=False)
    op.create_index(op.f('ix_sde_stations_solar_system_id'), 'sde_stations', ['solar_system_id'], unique=False)
    op.create_table('sde_types',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('market_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_index(op.f('ix_sde_types_market_group_id'), 'sde_types', ['market_group_id'], unique=False)
    op.create_index(op.f('ix_sde_types_name'), 'sde_types', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=True),
    sa.Column('character_name', sa.String(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_character_id'), 'users', ['character_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_character_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sde_types_name'), table_name='sde_types')
    op.drop_index(op.f('ix_sde_types_market_group_id'), table_name='sde_types')
    op.drop_table('sde_types')
    op.drop_index(op.f('ix_sde_stations_solar_system_id'), table_name='sde_stations')
    op.drop_index(op.f('ix_sde_stations_name'), table_name='sde_stations')
    op.drop_table('sde_stations')
    op.drop_index(op.f('ix_sde_solar_systems_region_id'), table_name='sde_solar_systems')
    op.drop_index(op.f('ix_sde_solar_systems_name'), table_name='sde_solar_systems')
    op.drop_table('sde_solar_systems')
    op.drop_table('sde_solar_system_jumps')
    op.drop_index(op.f('ix_sde_regions_name'), table_name='sde_regions')
    op.drop_table('sde_regions')
    op.drop_index(op.f('ix_sde_market_groups_parent_group_id'), table_name='sde_market_groups')
    op.drop_table('sde_market_groups')
    op.drop_table('region_fetch_status')
    op.drop_table('region_etags')
    op.drop_index(op.f('ix_market_orders_updated_at'), table_name='market_orders')
    op.drop_index('ix_market_orders_type_region_buy_issued', table_name='market_orders')
    op.drop_index(op.f('ix_market_orders_type_id'), table_name='market_orders')
    op.drop_index(op.f('ix_market_orders_region_id'), table_name='market_orders')
    op.drop_table('market_orders')
    op.drop_index(op.f('ix_market_history_type_id'), table_name='market_history')
    op.drop_index('ix_market_history_region_type_date', table_name='market_history')
    op.drop_index(op.f('ix_market_history_region_id'), table_name='market_history')
    op.drop_table('market_history')
    # ### end Alembic commands ###
