"""Add unique constraint to market_history

Revision ID: 6c65d5fb3c1b
Revises: fcf08f87481f
Create Date: 2025-12-03 18:41:50.869116

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c65d5fb3c1b"
down_revision: Union[str, Sequence[str], None] = "fcf08f87481f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
