"""unique region type date index

Revision ID: 8e5bb3917922
Revises: 5b47058a4173
Create Date: 2025-12-03 16:01:48.160147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e5bb3917922'
down_revision: Union[str, Sequence[str], None] = '5b47058a4173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('market_history', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_index(op.f('ix_market_history_region_type_date'), table_name='market_history')
    op.create_unique_constraint('uq_market_history_region_type_date', 'market_history', ['region_id', 'type_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_market_history_region_type_date', 'market_history', type_='unique')
    op.create_index(op.f('ix_market_history_region_type_date'), 'market_history', ['region_id', 'type_id', 'date'], unique=True)
    op.alter_column('market_history', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###
