"""unique region type date index

Revision ID: fcf08f87481f
Revises: 3a78ca2ad280
Create Date: 2025-12-03 14:00:19.668194

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fcf08f87481f"
down_revision: Union[str, Sequence[str], None] = "3a78ca2ad280"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_market_history_region_type_date"), table_name="market_history")
    op.create_index(
        "ix_market_history_region_type_date",
        "market_history",
        ["region_id", "type_id", "date"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_market_history_region_type_date", table_name="market_history")
    op.create_index(
        op.f("ix_market_history_region_type_date"),
        "market_history",
        ["region_id", "type_id", "date"],
        unique=False,
    )
    # ### end Alembic commands ###
